name: publish

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: volta-cli/action@v1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ secrets.PNPM_VERSION }}
          run_install: true

      - run: pnpm lint
      - run: pnpm test

  publish-npm:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: volta-cli/action@v1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ secrets.PNPM_VERSION }}
          run_install: true

      - run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          pnpm package
          pnpm publish ./package